CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000

# 物理レイアウト関連を強制無効化
CONFIG_ZMK_PHYSICAL_LAYOUTS=n
CONFIG_ZMK_KSCAN=n
CONFIG_ZMK_DRIVERS_KSCAN=n
