name: Build ZMK Firmware
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          ref: main
          path: zmk

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install west and dependencies
        run: |
          pip install west requests patool

      - name: West Init & Update
        run: |
          cd zmk
          west init -l app
          west update

      - name: Install Zephyr SDK
        run: |
          cd zmk
          west sdk install

      - name: Build
        run: |
          cd zmk/app
          west build -b xiao_ble -- -DZMK_CONFIG=${{ github.workspace }}/config

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: zmk/app/build/zephyr/zmk.uf2
